### ISSUE TITLE
Showing 0 Achievements

### ISSUE THREAD

**Issue by blehmonster** [jwld/completionism-issues#16]
Hello,

I have added my battletag, and everything shows except achievements and toys.  I understand toys aren't shown because they can't be grabbed from an external source.  Achievements used to work (prior to using battle tag).  Is there something I can toggle or change to fix this?

Thanks.

**Comment by jwld** [comment]
I think I might know what's going on - I'll let you know once I've updated it!

**Comment by jwld** [comment]
@blehmonster I've pushed an update, let me know if that's fixed it for you

**Comment by blehmonster** [comment]
No change here, unfortunately.  I refreshed my battle tag and did a cacheless browser reload.  Still showing 0 achievements from any expansion.

**Comment by jwld** [comment]
I've pushed another update, how about now?

**Comment by blehmonster** [comment]
Works now, thank you!
